
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: kitsunekomix_app
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
      - ./comics:/app/comics
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      ENV: development
      PORT: 8000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - kitsune_network

  redis:
    image: redis:8.2.1-alpine
    container_name: kitsune_redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - kitsune_network

volumes:
  redis_data:

networks:
  kitsune_network:
    driver: bridge