services:
  # Nuxt Application Service (Development)
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: kitsunekomix_nuxt_app
    ports:
      - "3000:3000"  # Nuxt app port
      - "24678:24678"  # Nuxt debug port
    volumes:
      - /Users/alexismontes/Documents/KitsuneKomix_Volumes/cache:/app/cache
      - /Users/alexismontes/Documents/KitsuneKomix_Volumes/comics:/app/comics
      - /Users/alexismontes/Documents/KitsuneKomix_Volumes/config:/app/config
    environment:
      ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      NUXT_DEV_TOOLS: "true"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - kitsune_network
    # Dockerfile handles the command, no need to override
    # command: ["deno", "task", "dev"]
  redis:
    image: redis:8.2.1-alpine
    container_name: kitsune_redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - kitsune_network

volumes:
  redis_data:
  nuxt_build_cache:
  nuxt_output_cache:

networks:
  kitsune_network:
    driver: bridge
