services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      target: api
    container_name: kitsune_komix_api
    ports:
      - "8001:8001"
    volumes:
      - /Users/alexismontes/Documents/KitsuneKomix_Volumes/cache:/app/data/cache
      - /Users/alexismontes/Documents/KitsuneKomix_Volumes/comics:/app/data/comics
      - /Users/alexismontes/Documents/KitsuneKomix_Volumes/config:/app/data/config
    environment:
      MODE: development
    restart: unless-stopped
    networks:
      - kitsune_network

networks:
  kitsune_network:
    driver: bridge