services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${BUILD_TARGET:-production}
    container_name: kitsunekomix_app
    ports:
      - "8000:8000"
      # Debug port (only used in development)
      - "${DEBUG_PORT:-9229}:9229"
    volumes:
      - ./cache:/app/cache
      - ./comics:/app/comics
      - ./config:/app/config
      - ./logs:/app/logs
      # Mount source code for development hot reloading
      - ./src:/app/src
      - ./deno.json:/app/deno.json
      - ./drizzle.config.ts:/app/drizzle.config.ts
      # Mount drizzle migrations for development
      - ./drizzle:/app/drizzle
    environment:
      ENV: ${NODE_ENV:-production}
      PORT: 8000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - kitsune_network

  # Web client service (only runs in development)
  web-client:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: web-client-dev
    container_name: kitsunekomix_web_client
    ports:
      - "5173:5173"
    volumes:
      # Mount web client source for hot reloading
      - ./web/kitsune-web-client:/app/web/kitsune-web-client
      # Mount node_modules as named volume for performance
      - web_client_node_modules:/app/web/kitsune-web-client/node_modules
    environment:
      NODE_ENV: development
      # API endpoint for the web client
      VITE_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - kitsune_network

  redis:
    image: redis:8.2.1-alpine
    container_name: kitsune_redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - kitsune_network

volumes:
  redis_data:
  web_client_node_modules:

networks:
  kitsune_network:
    driver: bridge
