
export const QueryableColumns = {
	comics: {
		filter: {
			id: "id",
			seriesId: "seriesId",
			hash: "hash",
			title: "title",
			issueNumber: "issueNumber",
			volume: "volume",
			alternateSeries: "alternateSeries",
			alternateIssueNumber: "alternateIssueNumber",
			fileSize: "fileSize",
			summary: "summary",
			notes: "notes",
			year: "year",
			month: "month",
			day: "day",
			publisher: "publisher",
			publicationDate: "publicationDate",
			scanInfo: "scanInfo",
			language: "language",
			format: "format",
			blackAndWhite: "blackAndWhite",
			manga: "manga",
			readingDirection: "readingDirection",
			review: "review",
			ageRating: "ageRating",
			communityRating: "communityRating",
			createdAt: "createdAt",
			updatedAt: "updatedAt",
		},
		sort: {
			title: "title",
			issueNumber: "issueNumber",
			volume: "volume",
			alternateSeries: "alternateSeries",
			alternateIssueNumber: "alternateIssueNumber",
			fileSize: "fileSize",
			year: "year",
			month: "month",
			day: "day",
			publisher: "publisher",
			publicationDate: "publicationDate",
			language: "language",
			format: "format",
			blackAndWhite: "blackAndWhite",
			manga: "manga",
			readingDirection: "readingDirection",
			ageRating: "ageRating",
			communityRating: "communityRating",
			createdAt: "createdAt",
			updatedAt: "updatedAt",
		},
	},
} as const;