FROM denoland/deno:2.3.6

WORKDIR /app

USER deno

# Copy your source code
COPY . .

# Expose the port your Oak/Deno app will run on
EXPOSE 3000

CMD ["run", "--allow-net", "--allow-read", "--allow-write", "--allow-ffi", "--allow-env", "main.ts"]