/**
 * Interface representing a comic book.
 * @interface ComicBook
 * @property {number | null} id - The unique identifier for the comic book, or null if not yet inserted.
 * @property {string | null} title - The title of the comic book.
 * @property {string} file_name - The name of the comic book file.
 * @property {string} file_hash - The hash of the comic book file for integrity checks.
 * @property {string} file_path - The path to the comic book file.
 * @property {Date | null} timestamp - The timestamp of when the comic book was added or last modified, or null if not applicable.
 * @property {number} metadata_id - The unique identifier for the metadata associated with the comic book.
 * @property {number} series_id - The unique identifier for the comic series this book belongs to.
 */
export interface ComicBook {
  id: number | null;
  title: string | null;
  file_name: string;
  file_hash: string;
  file_path: string;
  timestamp: Date | null;
  metadata_id: number;
  series_id: number;
}

/**
 * Type for inserting a new comic book into the database.
 * This type omits the 'id' property, as it will be generated by the database.
 * @type ComicBookInsert
 * @property {string} title - The title of the comic book.
 * @property {string} file_name - The name of the comic book file.
 * @property {string} file_hash - The hash of the comic book file for integrity checks.
 * @property {string} file_path - The path to the comic book file.
 * @property {Date | null} timestamp - The timestamp of when the comic book was added or last modified, or null if not applicable.
 * @property {number} metadata_id - The unique identifier for the metadata associated with the comic book.
 * @property {number} series_id - The unique identifier for the comic series this book belongs to.
 */
export type ComicBookInsert = Omit<ComicBook, 'id'> & { id?: number | null };