
/**
 * Interface representing the metadata of a comic_metadata record.
 * 
 * @interface ComicMetadata
 * @property {number} id - The unique identifier for the comic.
 * @property {string} title - The title of the comic.
 * @property {string} series - The series to which the comic belongs.
 * @property {string} number - The issue number of the comic.
 * @property {number} count - The total number of issues in the series.
 * @property {string} volume - The volume of the comic.
 * @property {string} alternateSeries - An alternate series name, if applicable.
 * @property {string} alternateNumber - An alternate issue number, if applicable.
 * @property {string} alternateVolume - An alternate volume, if applicable.
 * @property {string} summary - A brief summary of the comic's content.
 * @property {string} notes - Additional notes about the comic.
 * @property {number} year - The year of publication.
 * @property {number} month - The month of publication.
 * @property {number} day - The day of publication.
 * @property {string} website - The official website related to the comic.
 * @property {number} page_count - The total number of pages in the comic.
 * @property {string} language - The language in which the comic is published.
 * @property {string} format - The format of the comic (e.g., digital, print).
 * @property {boolean} blackAndWhite - Indicates if the comic is in black andwhite.
 * @property {boolean} manga - Indicates if the comic is a manga.
 * @property {string} scanInfo - Information about the scan, if applicable.
 * @property {number | null} storyArcId - The ID of the story arc, if applicable. Can be null if not part of a story arc.
 * @property {number} communityRating - The community rating of the comic, typically on a scale (e.g., 1 to 5).
 * @property {string} mainCharacter - The main character featured in the comic.
 * @property {string} review - A review of the comic, if available.
 * @property {string} gtin - The Global Trade Item Number (GTIN) for the comic, if applicable.
 */
export interface ComicMetadata {
    id: number | null; // This will be set after inserting the metadata
    title: string | null; // Title can be null if not set
    series: string;
    number: string | null; // Number can be null if not set
    count: number | null;
    volume: string | null;
    alternateSeries: string | null;
    alternateNumber: string | null;
    alternateVolume: string | null;
    summary: string | null;
    notes: string | null;
    year: number | null;
    month: number | null;
    day: number | null;
    website: string | null;
    page_count: number | null;
    language: string | null;
    format: string | null;
    blackAndWhite: boolean | null;
    manga: boolean | null;
    mangaDirection: string | null; // Added for manga direction
    scanInfo: string | null;
    storyArcId: number | null;
    communityRating: number | null;
    mainCharacter : string | null;
    review: string | null;
    gtin: string | null;
}

/**
 * Type for inserting a new comic metadata record into the database.
 * This type omits the 'id' property, as it will be generated by the database.
 * 
 * @type ComicMetadataInsert
 * @property {number | null} id - Optional ID for the comic metadata, will be set after insertion.
 * @property {string | null} title - Optional title for the comic, will be set after insertion.
 * @property {string} series - The series to which the comic belongs.
 * @property {string | null} number - Optional issue number for the comic, will be set after insertion.
 * @property {number | null} count - Optional total number of issues in the series, will be set after insertion.
 * @property {string | null} volume - Optional volume for the comic, will be set after insertion.
 * @property {string | null} alternateSeries - Optional alternate series name, will be set after insertion.
 * @property {string | null} alternateNumber - Optional alternate issue number, will be set after insertion.
 * @property {string | null} alternateVolume - Optional alternate volume, will be set after insertion.
 * @property {string | null} summary - Optional summary of the comic, will be set after insertion.
 * @property {string | null} notes - Optional additional notes about the comic, will be set after insertion.
 * @property {number | null} year - Optional year of publication, will be set after insertion.
 * @property {number | null} month - Optional month of publication, will be set after insertion.
 * @property {number | null} day - Optional day of publication, will be set after insertion.
 * @property {string | null} website - Optional official website related to the comic, will be set after insertion.
 * @property {number | null} page_count - Optional total number of pages in the comic, will be set after insertion.
 * @property {string | null} language - Optional language in which the comic is published, will be set after insertion.
 * @property {string | null} format - Optional format of the comic (e.g., digital, print), will be set after insertion.
 * @property {boolean | null} blackAndWhite - Optional flag indicating if the comic is in black and white, will be set after insertion.
 * @property {boolean | null} manga - Optional flag indicating if the comic is a manga, will be set after insertion.
 * @property {string | null} mangaDirection - Optional direction for manga (e.g., left-to-right, right-to-left), will be set after insertion.
 * @property {string | null} scanInfo - Optional information about the scan, will be set after insertion.
 * @property {number | null} storyArcId - Optional ID of the story arc, will be set after insertion. Can be null if not part of a story arc.
 * @property {number | null} communityRating - Optional community rating of the comic, will be set after insertion.
 * @property {string | null} mainCharacter - Optional main character featured in the comic, will be set after insertion.
 * @property {string | null} review - Optional review of the comic, will be set after insertion.
 * @property {string | null} gtin - Optional Global Trade Item Number (GTIN) for the comic, will be set after insertion.
 */
export type ComicMetadataInsert = Omit<ComicMetadata, 'id'> & { id?: number | null };