// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table app_setings {
  id integer [primary key]
  key text [not null, unique]
  value text
  admin_only bool
  created_at date
  updated_at date
}

Table users {
  id integer [primary key]
  username varchar
  first_name text
  last_name text
  password_hash text [not null]
  email text
  admin book
  created_at date
  updated_at date
}

Table comic_libraries {
  id integer [primary key]
  name text [not null]
  path text [not null]
  description text
  enabled bool [default: 1]
  changed_at date
  updated_at date
}

Table comic_series {
  id integer [primary key]
  name text [not null]
  description text
  folder_path text [unique]
  created_at date
  updated_at date
}

Table comic_books {
  id integer [primary key]
  library_id integer [not null]
  file_path text [not null]
  title text
  series text
  issue_number text
  volume text
  publisher text
  puplication_date text
  tags text
  read integer [not null, default:0]

}

Table comic_series_books {
  id integer [primary key]
  comic_series_id integer [not null]
  comic_book_id integer [not null]
  created_at date
  updated_at date
}

Table comic_pages {
  id integer [primary key]
  comicbook_id int
  file_path string
  page_number integer
  type string
  double_page boolean
  length int
  width int
  hash string
  file_size int
  created_at date
  update_at date
}

Table comic_book_covers {
  id integer [primary key]
  comic_page_id integer
  file_path string
  created_at date
  updated_at date
}

Table comic_book_thumbnails {
  id integer [primary key]
  comic_book_cover_id integer
  file_path string [note: "Should only reflect path to thumbnail in cache"]
  created_at date
  updated_at date
}

Table comic_web_links {
  id integer [primary key]
  comicbook_id integer
  url string
  description text
  created_at date
  updated_at date
}

Table comic_writers {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_writers {
  id integer [primary key]
  comicbook_id integer
  writer_id integer
  created_at date
  updated_at date
}

Table comic_pencillers {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_pencillers {
  id integer [primary key]
  comicbook_id integer
  penciller_id integer
  created_at date
  updated_at date
}

Table comic_inkers {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_inkers {
  id integer [primary key]
  comicbook_id integer
  inker_id integer
  created_at date
  updated_at date
}

Table comic_letterers {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_letterers {
  id integer [primary key]
  comicbook_id integer
  letterer_id integer
  created_at date
  updated_at date
}

Table comic_editors {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_editors {
  id integer [primary key]
  comicbook_id integer
  editor_id integer
  created_at date
  updated_at date
}

Table comic_cover_artists {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_cover_artists {
  id integer [primary key]
  comicbook_id integer
  comic_cover_artist integer
}

Table comic_publishers {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_publishers {
  id integer [primary key]
  comicbook_id integer
  publisher_id integer
  created_at date
  updated_at date
}

Table comic_imprints {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_imprints {
  id integer [primary key]
  comicbook_id integer
  imprint_id integer
  created_at date
  updated_at date
}

Table comic_genres {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_genres {
  id integer [primary key]
  comicbook_id integer
  genre_id integer
  created_at date
  updated_at date
}

Table comic_characters {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_characters {
  id integer [primary key]
  comicbook_id integer
  character_id integer
  created_at date
  updated_at date
}

Table comic_teams {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_teams {
  id integer [primary key]
  comicbook_id integer
  team_id integer
  created_at date
  updated_at date
}

Table comic_story_arcs {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_story_arcs {
  id integer [primary key]
  comicbook_id integer
  story_arc_id integer
  created_at date
  updated_at date
}

Table comic_series_group {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_series_group {
  id integer [primary key]
  comicbook_id integer
  series_group_id integer
  created_at date
  updated_at date
}

Table comic_locations {
  id integer [primary key]
  name text [unique]
  description text
  created_at date
  updated_at date
}

Table comic_book_locations {
  id integer [primary key]
  comicbook_id integer
  location_id integer
}

Ref library_books: comic_libraries.id < comic_books.library_id

Ref comic_series_books_series: comic_series_books.comic_series_id > comic_series.id
Ref comic_series_books_book: comic_series_books.comic_book_id - comic_books.id

ref comic_book_web_links: comic_web_links.comicbook_id > comic_books.id

Ref comic_book_pages:  comic_pages.comicbook_id > comic_books.id
Ref comic_book_covers_pages: comic_book_covers.comic_page_id - comic_pages.id
Ref comic_book_thumbnails: comic_book_thumbnails.comic_book_cover_id - comic_book_covers.id

Ref comic_book_writers: comic_book_writers.writer_id > comic_writers.id
Ref comic_writer_books: comic_book_writers.comicbook_id > comic_books.id

ref comic_book_pencillers: comic_book_pencillers.penciller_id > comic_pencillers.id
ref comic_penciller_books: comic_book_pencillers.comicbook_id > comic_books.id

ref comic_book_inkers: comic_book_inkers.inker_id > comic_inkers.id
ref comic_inker_books: comic_book_inkers.comicbook_id > comic_books.id

ref comic_book_letterers: comic_book_letterers.letterer_id > comic_letterers.id
ref comic_letterer_books: comic_book_letterers.comicbook_id > comic_books.id

ref comic_book_editors: comic_book_editors.editor_id > comic_editors.id
ref comic_editor_books: comic_book_editors.comicbook_id > comic_books.id

ref comic_book_cover_artists: comic_book_cover_artists.comic_cover_artist > comic_cover_artists.id
ref comic_cover_artist_books: comic_book_cover_artists.comicbook_id > comic_books.id

ref comic_book_publishers: comic_book_publishers.publisher_id > comic_publishers.id
ref comic_publishers_books: comic_book_publishers.comicbook_id > comic_books.id

ref comic_book_imprints: comic_book_imprints.imprint_id > comic_imprints.id
ref comic_imprint_books: comic_book_imprints.comicbook_id > comic_books.id

ref comic_book_genres: comic_book_genres.genre_id >  comic_genres.id
ref comic_genre_books: comic_book_genres.comicbook_id > comic_books.id

ref comic_book_characters: comic_book_characters.character_id > comic_characters.id
ref comic_character_books: comic_book_characters.comicbook_id > comic_books.id

ref comic_book_teams: comic_book_teams.team_id > comic_teams.id
ref comic_team_books: comic_book_teams.comicbook_id > comic_books.id

ref comic_book_story_arcs: comic_book_story_arcs.story_arc_id > comic_story_arcs.id
ref comic_story_arc_books: comic_book_story_arcs.comicbook_id > comic_books.id

ref comic_book_series_groups: comic_book_series_group.series_group_id > comic_series_group.id
ref comic_series_group_books: comic_book_series_group.comicbook_id > comic_books.id

ref comic_book_locations: comic_book_locations.location_id > comic_locations.id
ref comic_location_books: comic_book_locations.comicbook_id > comic_books.id

